### ISSUE TITLE
Add support for building vanilla boxes

### ISSUE THREAD

**Issue by gusztavvargadr** [gusztavvargadr/packer#296]
### Discussed in https://github.com/gusztavvargadr/packer/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **JoelMiller74** November 21, 2021</sup>
I need Vagrant box images for testing in our DevOps pipelines. I love how you have built these images and keep them up to date every month using automation.
However, I run into issues with the fact that the base boxes with just Windows Server also includes chocolatey, OpenSSL, and Chef Client 17. I am testing with Chef Test-Kitchen and currently we require a lower version than newest (17). I wish we were on the newest version, but currently, we are stuck at version 14. When I use test-kitchen with the Windows Server images, I get issues because Chef Client 17 is already installed. I must uninstall it before running my recipes.
I am just looking at finding a way to build using this repo without any additional software like chocolatey, OpenSSL, Chef-Client, etc... on the built box. Test-Kitchen will automatically install the chef client and any additional software I need.
Is there a way to build Windows Server images without any of the Configuration Management tools installed? I am just looking for a vanilla installation.</div>

**Comment by JoelMiller74** [comment]
Just checking to see if you have any idea on timeline for this one yet. -Thanks!

**Comment by gusztavvargadr** [comment]
@JoelMiller74 I can probably start with this sometime in Feburary. Thanks for the patience.

**Comment by JoelMiller74** [comment]
Just additional info as I have a new use-case. We are working to migrate from using Chef to CINC (Cinc Is Not Chef). It is an opensource version of Chef. In this case, I spin up a vagrant machine with Test-Kitchen and the Windows client already has Chef 17 and it creates problems when trying to get the CINC client installed.
-Thanks!

**Comment by gusztavvargadr** [comment]
@JoelMiller74 thanks for the update and sorry for the delay around this. You can try as a workaround in the meantime having a custom provisioning step with Test Kitchen to uninstall Chef.

Sorry again, I will try to get this done as soon as possible.

**Comment by DecoyJoe** [comment]
@JoelMiller74 I've worked around this by adding a lifecycle hook to uninstall Chef client on this box after it's created:

```yaml
platforms:
- name: windows-2022
  driver:
    box: gusztavvargadr/windows-server-2022-standard
    customize:
      memory: 1536
  lifecycle:
    post_create:
    - remote: | # Until there is a vanilla box available: https://github.com/gusztavvargadr/packer/issues/296
        $app = Get-WmiObject -Class 'Win32_Product' -Filter "Name LIKE 'Chef Infra Client v%'"
        $app.Uninstall() | Out-Null
  transport:
    elevated: true
```
